version: '3.4'

services:
  backend1113:
    image: backend1113
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3113:3113
  mongodb:
    image: mongo:latest  # Replace with a specific version if needed
    volumes:
      - mongo-data:/data/db  # Persist data volume

volumes:
  mongo-data:  # Define the volume